force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>תיאור</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/JoinedDate__c.field-meta.xml
<CustomField>
    <fullName>JoinedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>הצטרף לבנק</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>מספר עובדים</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/Customer_External__x.object-meta.xml
<CustomObject>
    <externalDataSource>ExternalDataSource1</externalDataSource>
    <externalName>Customer__c</externalName>
    <label>Customer External</label>
    <pluralLabel>Customer Externals</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_External__x/fields/BusinessSector__c.field-meta.xml
<CustomField>
    <fullName>BusinessSector__c</fullName>
    <externalDeveloperName>BusinessSector</externalDeveloperName>
    <label>Business  Sector</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>20</length>
    <referenceTargetField>Customer__c.GUID__c</referenceTargetField>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Customer Externals</relationshipLabel>
    <relationshipName>Customer_Externals</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/ManagingCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>ManagingCustomerNumber__c</fullName>
    <externalDeveloperName>ManagingCustomerNumber</externalDeveloperName>
    <label>Managing Customer Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/Slice__c.field-meta.xml
<CustomField>
    <fullName>Slice__c</fullName>
    <externalDeveloperName>Slice</externalDeveloperName>
    <label>Slice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/TargetSector__c.field-meta.xml
<CustomField>
    <fullName>TargetSector__c</fullName>
    <externalDeveloperName>TargetSector</externalDeveloperName>
    <label>Target Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NIT_0Enc_1ODATA_CTR.cls
public with sharing class NIT_0Enc_1ODATA_CTR {
    /**
     * Class Variables
     */
    
    /**
     * Public variables
     */
    public Customer__c          customer            {get; set;}
    public Customer_External__x customerExternal    {get; set;}

    /**
     * Private variables
     */
    private String customerId;

    
    /**
     * Class contructor
     */
    public NIT_0Enc_1ODATA_CTR() {
        init();
    }

    /**
     * Initialize page variables
     */
    private void init(){
        try{
            this.customer = new Customer__c();
            this.customerExternal = new Customer_External__x();
    
            this.customer = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, GUID__c FROM Customer__c LIMIT 1];        
            this.customerExternal = [SELECT TargetSector__c, Slice__c, ManagingCustomerNumber__c, BusinessSector__c FROM Customer_External__x LIMIT 1];
        }catch(Exception c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'External system error'));
        }
    }

}