force-app/main/default/objects/Contact/fields/disable_WF__c.field-meta.xml
<CustomField>
    <fullName>disable_WF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>disable_WF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אחר</fullName>
                <default>true</default>
                <label>אחר</label>
            </value>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>מזהה חיצוני</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/AnnualRevenue__c.field-meta.xml
<CustomField>
    <fullName>AnnualRevenue__c</fullName>
    <label>מחזור שנתי</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>תיאור</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/disable_WF__c.field-meta.xml
<CustomField>
    <fullName>disable_WF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>disable_WF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>תחום עיסוק</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/JoinedDate__c.field-meta.xml
<CustomField>
    <fullName>JoinedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>הצטרף לבנק</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>מספר עובדים</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NIT_NADAVFLOWS_CTR.cls
global with sharing class NIT_NADAVFLOWS_CTR {

	/**
	 * Public variables
	 */
	public Customer__c 		customer 			{get; set;}
	public Contact 			currentContact 		{get; set;}
	public String 			dataToUpdate 		{get; set;}

	public NIT_NADAVFLOWS_CTR() {
		init();
	}

	/**
	 * Initialize page variables
	 */
	private void init(){
		this.customer = new Customer__c();
		this.currentContact = new Contact();
		this.dataToUpdate = '';

		String customerId = apexpages.currentpage().getparameters().get('customerId');
		String contactId = apexpages.currentpage().getparameters().get('contactId');

		if(!String.isEmpty(customerId)){
			this.customer = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, FullName__c, AnnualRevenue__c,
						Industry__c, disable_WF__c FROM Customer__c WHERE Id =: customerId LIMIT 1];
		}
		else{
			this.customer = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, FullName__c, AnnualRevenue__c,
								Industry__c, disable_WF__c FROM Customer__c LIMIT 1];
		}

		if(!String.isEmpty(contactId)){
			this.currentContact = [SELECT Id, FirstName, LastName, Gender__c, GUID__c ,disable_WF__c FROM Contact WHERE Id =: contactId LIMIT 1];
		}
		else{
			this.currentContact = [SELECT Id, FirstName, LastName, Gender__c, GUID__c ,disable_WF__c FROM Contact LIMIT 1];
		}
	}

	/**
	 * runReadBatch call read batch operation
	 */
	public void runReadBatch(){
		NIT_Contact_Read_Batch bat = new NIT_Contact_Read_Batch();
		Database.executeBatch(bat);
	}

	/**
	 * runWriteBatch call write batch operation
	 */
	public void runWriteBatch(){
		NIT_Contact_Write_Batch bat = new NIT_Contact_Write_Batch();
		Database.executeBatch(bat);
	}

	/**
	 * updateCustomer update customer information
	 */
	public void updateCustomer(){
		System.debug('SFDC this.dataToUpdate: ' + this.dataToUpdate);
		Customer__c customer = (Customer__c)JSON.deserialize(this.dataToUpdate, Customer__c.class);
		Contact contacttre = (Contact)JSON.deserialize('test', Contact.class);
		customer.Id = this.customer.Id;
		System.debug('SFDC customer: ' + customer);
		update customer;
	}

	
	/**
	 * updateContact update currentContact information
	 */
	@RemoteAction
	global static void updateContact(Contact contactToUpdate){
		System.debug('SFDC objectToUpdate: ' + contactToUpdate);
		//update currentContact;
	}

}