force-app/main/default/objects/Contact/fields/disable_WF__c.field-meta.xml
<CustomField>
    <fullName>disable_WF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>disable_WF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אחר</fullName>
                <default>true</default>
                <label>אחר</label>
            </value>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>מזהה חיצוני</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/AnnualRevenue__c.field-meta.xml
<CustomField>
    <fullName>AnnualRevenue__c</fullName>
    <label>מחזור שנתי</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>תיאור</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/disable_WF__c.field-meta.xml
<CustomField>
    <fullName>disable_WF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>disable_WF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>תחום עיסוק</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/JoinedDate__c.field-meta.xml
<CustomField>
    <fullName>JoinedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>הצטרף לבנק</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>מספר עובדים</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NadavTestingClass.cls
//public with sharing class NadavTestingClass 
//{
//	public NadavTestingClass() 
//	{
//		contact_t con = (contact_t)JSON.deserialize('test', contact_t.class);
//	}

//	public void myJSONFunc()
//	{
//		contact_t con = (contact_t)JSON.deserialize('test', contact_t.class);
//	}
//}

global with sharing class NadavTestingClass {

	/**
	 * Public variables
	 */
	public customer__c 	customer_t 		{get; set;}
	public contact 		contact_t 		{get; set;}
	public String 		dataToUpdate 	{get; set;}

	public NadavTestingClass() {
		init();
	}

	/**
	 * Initialize page variables
	 */
	private void init(){
		this.customer_t = new customer__c();
		this.contact_t = new contact();
		this.dataToUpdate = '' ; //add inline comment

		String customer_tId = apexpages.currentpage().getparameters().get('customer_tId');
		String contact_tId = apexpages.currentpage().getparameters().get('contact_tId');

		if(!String.isEmpty(customer_tId)){
			this.customer_t = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, FullName__c, AnnualRevenue__c,
						Industry__c, disable_WF__c FROM customer__c WHERE Id =: customer_tId LIMIT 1];
		}
		else{
			this.customer_t = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, FullName__c, AnnualRevenue__c,
								Industry__c, disable_WF__c FROM customer__c LIMIT 1];
		}

		if(!String.isEmpty(contact_tId)){
			this.contact_t = [SELECT Id, FirstName, LastName, Gender__c, GUID__c ,disable_WF__c FROM contact WHERE Id =: contact_tId LIMIT 1];
		}
		else{
			this.contact_t = [SELECT Id, FirstName, LastName, Gender__c, GUID__c ,disable_WF__c FROM contact LIMIT 1];
		}
	}

	/**
	 * runReadBatch call read batch operation
	 */
	public void runReadBatch(){
		NIT_contact_Read_Batch bat = new NIT_contact_Read_Batch();
		Database.executeBatch(bat);
	}

	/**
	 * runWriteBatch call write batch operation
	 */
	public void runWriteBatch(){
		NIT_contact_Write_Batch bat = new NIT_contact_Write_Batch();
		Database.executeBatch(bat);
	}

	/**
	 * updatecustomer_t update customer_t information
	 */
	public void updatecustomer_t(){
		System.debug('SFDC this.dataToUpdate: ' + this.dataToUpdate);
		//customer_t__c customer_t = (customer_t__c)JSON.deserialize(this.dataToUpdate, customer_t__c.class);
		//contact_t contact_ttre = (contact_t)JSON.deserialize('test', contact_t.class);
		//customer_t.Id = this.customer_t.Id;
		//System.debug('SFDC customer_t: ' + customer_t);
		//update customer_t;
	}

	public void updatecustomer_t1()
	{
		SObject con = (Contact)JSON.deserialize('test', Contact.class);
	}

	
	/**
	 * updatecontact_t update contact_t information
	 */
	@RemoteAction
	global static void updatecontact(contact contact_tToUpdate){
		System.debug('SFDC objectToUpdate: ' + contact_tToUpdate);
		//contact_t customer_t = (contact_t)JSON.deserialize('test', contact_t.class);
		//update contact_t;
	}

}