force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אחר</fullName>
                <default>true</default>
                <label>אחר</label>
            </value>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>מזהה חיצוני</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact__x/Contact__x.object-meta.xml
<CustomObject>
    <externalDataSource>ExternalDataSource1</externalDataSource>
    <externalName>Contact</externalName>
    <label>External Contact</label>
    <pluralLabel>External  Contacts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact__x/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <externalDeveloperName>Age</externalDeveloperName>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/BankingType__c.field-meta.xml
<CustomField>
    <fullName>BankingType__c</fullName>
    <externalDeveloperName>BankingType</externalDeveloperName>
    <label>Banking Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/CountryOfResidency__c.field-meta.xml
<CustomField>
    <fullName>CountryOfResidency__c</fullName>
    <externalDeveloperName>CountryOfResidency</externalDeveloperName>
    <label>Country  Of Residency</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/EnglishFirstName__c.field-meta.xml
<CustomField>
    <fullName>EnglishFirstName__c</fullName>
    <externalDeveloperName>EnglishFirstName</externalDeveloperName>
    <label>English First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/EnglishLastName__c.field-meta.xml
<CustomField>
    <fullName>EnglishLastName__c</fullName>
    <externalDeveloperName>EnglishLastName</externalDeveloperName>
    <label>English Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/CompanyStartedDate__c.field-meta.xml
<CustomField>
    <fullName>CompanyStartedDate__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Company Started Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>תיאור</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>תחום עיסוק</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/JoinedDate__c.field-meta.xml
<CustomField>
    <fullName>JoinedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>הצטרף לבנק</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>מספר עובדים</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NIT_5Enc_1ODATA_CTR.cls
public with sharing class NIT_5Enc_1ODATA_CTR {
    /**
     * Class Variables
     */
    
    /**
     * Public variables
     */
    public Customer__c  customer            {get; set;}
    public Contact      contact             {get; set;}
    public Contact__x   contactExternal     {get; set;}

    
    /**
     * Class contructor
     */
    public NIT_5Enc_1ODATA_CTR() {
        init();
    }

    /**
     * Initialize page variables
     */
    private void init(){
        this.customer = new Customer__c();
        this.contact = new Contact();
        this.contactExternal = new Contact__x();

        String customerId = apexpages.currentpage().getparameters().get('customerId');
        String contactId = apexpages.currentpage().getparameters().get('contactId');
        try{
            this.customer = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, FullName__c, CompanyStartedDate__c,
                                    Industry__c FROM Customer__c LIMIT 1];
            this.contact = [SELECT Id, FirstName, LastName, Gender__c, GUID__c FROM Contact LIMIT 1];

        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No records to display'));
        }

        try{

                this.contactExternal = [SELECT BankingType__c, Age__c, CountryOfResidency__c, EnglishFirstName__c, EnglishLastName__c FROM Contact__x LIMIT 1];
        }
        catch(Exception c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'External system error'));
        }
    }
}