force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אחר</fullName>
                <default>true</default>
                <label>אחר</label>
            </value>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IDNumber__c.field-meta.xml
<CustomField>
    <fullName>IDNumber__c</fullName>
    <label>מספר ת.ז</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NIT_Contact_Read_Batch.cls
global class NIT_Contact_Read_Batch implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id, FirstName, LastName, Gender__c, Birthdate, Email, Phone, IDNumber__c FROM Contact';
	
	global NIT_Contact_Read_Batch() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('SF: Start Contact Read Batch');
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Contact> scope) {
   		for(Contact contact: scope){
   			System.debug('*************************************************');
			System.debug(contact);
			System.debug('+++++++++++++++++++++++++++++++++++++++++++++++++');
   		}
	}
	
	global void finish(Database.BatchableContext BC) {
		System.debug('SF: Finish Contact Read Batch');
	}
	
}