force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אחר</fullName>
                <default>true</default>
                <label>אחר</label>
            </value>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IDNumber__c.field-meta.xml
<CustomField>
    <fullName>IDNumber__c</fullName>
    <label>מספר ת.ז</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NIT_Contact_Write_Batch.cls
global class NIT_Contact_Write_Batch implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id, FirstName, LastName, Gender__c, Birthdate, Email, Phone, IDNumber__c FROM Contact';
	
	global NIT_Contact_Write_Batch() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('SF: Start Contact Write Batch');
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Contact> scope) {
   		List<Contact> contactList = new List<Contact>();

   		for(Contact contact: scope){
   			if(!String.isEmpty(contact.FirstName)){
   				contact.FirstName = contact.FirstName + '_Batch';
   			}
   			if(!String.isEmpty(contact.LastName)){
   				contact.LastName = contact.LastName + '_Batch';
   			}
   			if(contact.Birthdate != null){
   				contact.Birthdate = contact.Birthdate.addDays(3);
   			}

   			System.debug('*************************************************');
			System.debug(contact);
			System.debug('+++++++++++++++++++++++++++++++++++++++++++++++++');

   			contactList.add(contact);
   		}

   		update contactList;
	}
	
	global void finish(Database.BatchableContext BC) {
		System.debug('SF: Finish Contact Write Batch');
	}
	
}