force-app/main/default/objects/Contact/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>מזהה חיצוני</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact__x/Contact__x.object-meta.xml
<CustomObject>
    <externalDataSource>ExternalDataSource1</externalDataSource>
    <externalName>Contact</externalName>
    <label>External Contact</label>
    <pluralLabel>External  Contacts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact__x/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <externalDeveloperName>Age</externalDeveloperName>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/BankingType__c.field-meta.xml
<CustomField>
    <fullName>BankingType__c</fullName>
    <externalDeveloperName>BankingType</externalDeveloperName>
    <label>Banking Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/CountryOfResidency__c.field-meta.xml
<CustomField>
    <fullName>CountryOfResidency__c</fullName>
    <externalDeveloperName>CountryOfResidency</externalDeveloperName>
    <label>Country  Of Residency</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/EnglishFirstName__c.field-meta.xml
<CustomField>
    <fullName>EnglishFirstName__c</fullName>
    <externalDeveloperName>EnglishFirstName</externalDeveloperName>
    <label>English First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact__x/fields/EnglishLastName__c.field-meta.xml
<CustomField>
    <fullName>EnglishLastName__c</fullName>
    <externalDeveloperName>EnglishLastName</externalDeveloperName>
    <label>English Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>תיאור</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer__c/fields/JoinedDate__c.field-meta.xml
<CustomField>
    <fullName>JoinedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>הצטרף לבנק</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>מספר עובדים</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/Customer_External__x.object-meta.xml
<CustomObject>
    <externalDataSource>ExternalDataSource1</externalDataSource>
    <externalName>Customer__c</externalName>
    <label>Customer External</label>
    <pluralLabel>Customer Externals</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_External__x/fields/BusinessSector__c.field-meta.xml
<CustomField>
    <fullName>BusinessSector__c</fullName>
    <externalDeveloperName>BusinessSector</externalDeveloperName>
    <label>Business  Sector</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>20</length>
    <referenceTargetField>Customer__c.GUID__c</referenceTargetField>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Customer Externals</relationshipLabel>
    <relationshipName>Customer_Externals</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/ManagingCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>ManagingCustomerNumber__c</fullName>
    <externalDeveloperName>ManagingCustomerNumber</externalDeveloperName>
    <label>Managing Customer Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/Slice__c.field-meta.xml
<CustomField>
    <fullName>Slice__c</fullName>
    <externalDeveloperName>Slice</externalDeveloperName>
    <label>Slice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_External__x/fields/TargetSector__c.field-meta.xml
<CustomField>
    <fullName>TargetSector__c</fullName>
    <externalDeveloperName>TargetSector</externalDeveloperName>
    <label>Target Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NIT_0Enc_2ODATA_CTR.cls
public with sharing class NIT_0Enc_2ODATA_CTR {
    /**
     * Class Variables
     */
    
    /**
     * Public variables
     */
    public Customer__c          customer            {get; set;}
    public Contact              contact             {get; set;}
    public Customer_External__x customerExternal    {get; set;}
    public Contact__x           contactExternal     {get; set;}
    
    /**
     * Class contructor
     */
    public NIT_0Enc_2ODATA_CTR() {
        init();
    }

    /**
     * Initialize page variables
     */
    private void init(){
        this.customer = new Customer__c();
        this.contact = new Contact();
        this.customerExternal = new Customer_External__x();
        this.contactExternal = new Contact__x();

        String customerId = apexpages.currentpage().getparameters().get('customerId');
        String contactId = apexpages.currentpage().getparameters().get('contactId');
        
        try{        
            this.customer = [SELECT Id, Name, JoinedDate__c, Description__c, NumberOfEmployees__c, Phone__c, GUID__c FROM Customer__c LIMIT 1];
            this.contact = [SELECT Id, FirstName, GUID__c FROM Contact LIMIT 1];        
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No records to display'));
        }

        try{
            this.customerExternal = [SELECT TargetSector__c, Slice__c, ManagingCustomerNumber__c, BusinessSector__c FROM Customer_External__x LIMIT 1];
            this.contactExternal = [SELECT BankingType__c, Age__c, CountryOfResidency__c, EnglishFirstName__c, EnglishLastName__c FROM Contact__x LIMIT 1];
        }catch(Exception c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'External system error'));
        }
    }
}